"""pad display name

Revision ID: 726857c6f636
Revises: 610b7d4ad610
Create Date: 2026-06-17 11:17:44.381496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '726857c6f636'
down_revision: Union[str, None] = '610b7d4ad610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pads', sa.Column('name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pads', 'name')
    # ### end Alembic commands ###
